#!/usr/bin/with-contenv bashio
# Populates config/.env and config/speakers.json from the add-on's Configuration
# tab, then hands off to the same server.js every other deployment method runs.
# This is the ONLY job this wrapper does — MASS_TOKEN login, the SUPERVISOR_TOKEN
# restart cascade, and Ingress-relative fetches are all native in the app itself.

CONFIG_PATH=/app/config
ENV_FILE="${CONFIG_PATH}/.env"

# No speakers.json handling here on purpose — v4 auto-discovery (server.js)
# derives the subnet from MASS_IP and finds speakers itself on every boot.
# host_network: true in config.yaml is what gives it real LAN access to do so.

bashio::log.info "Writing config/.env from add-on options..."

# Derived from server.js itself so this can never drift out of sync with the
# app's own ENV_SCHEMA_VERSION constant (a hardcoded third copy here is what
# caused the v4.0-vs-v4 mismatch that hard-halted every boot).
ENV_SCHEMA_VERSION="$(sed -n 's/.*ENV_SCHEMA_VERSION = "\(.*\)".*/\1/p' /app/server.js)"

# Auto-detect this host's address when app_ip is left blank — host_network:
# true means this container's "default" interface IS the HA host's real LAN
# interface, so Supervisor's own network info gives us the right answer
# without asking the user to type an IP they already told HA about.
APP_IP="$(bashio::config 'app_ip')"
APP_IP_AUTODETECTED=false
if [ -z "${APP_IP}" ]; then
    APP_IP="$(bashio::network.ipv4_address 2>/dev/null | head -n1 | cut -d'/' -f1)"
    APP_IP_AUTODETECTED=true
    bashio::log.info "app_ip not set — auto-detected host address: ${APP_IP}"
fi

# mass_ip defaults to the same host address when left blank, since the common
# case for installing this AS an HA add-on is Music Assistant running on the
# same instance. Users with MASS on a separate machine still override it.
MASS_IP="$(bashio::config 'mass_ip')"
MASS_IP_AUTODETECTED=false
if [ -z "${MASS_IP}" ]; then
    MASS_IP="${APP_IP}"
    MASS_IP_AUTODETECTED=true
    bashio::log.info "mass_ip not set — defaulting to this host's address: ${MASS_IP}"
fi

# Not a user-editable option — Supervisor assigns this dynamically
# (config.yaml's ingress_port: 0) and guarantees it stays reserved for this
# add-on across every restart until uninstalled. See config.yaml's
# ingress_port comment for the full mechanism.
#
# Queried directly via curl+jq (GET /addons/self/info) rather than
# bashio::app.ingress_port — that helper isn't present in this base image's
# bundled bashio version (confirmed via a real boot failure: "bashio::app.
# ingress_port: command not found"). The .data unwrapping matches the same
# Supervisor API convention already used in routes/mass_utils.js's
# supervisorRequest()/discoverMusicAssistantAppSlug().
APP_PORT="$(curl -sf -H "Authorization: Bearer ${SUPERVISOR_TOKEN}" http://supervisor/addons/self/info 2>/dev/null | jq -r '.data.ingress_port // empty')"
if [ -z "${APP_PORT}" ]; then
    bashio::log.warning "Could not read the assigned ingress port from Supervisor — falling back to 8099."
    APP_PORT=8099
fi
MASS_PORT="$(bashio::config 'mass_port')"
MASS_USERNAME="$(bashio::config 'mass_username')"
MASS_PASSWORD="$(bashio::config 'mass_password')"
MASS_TOKEN="$(bashio::config 'mass_token')"

# Blank = auto (current MASS_IP-derived scan). Only needed when speakers live
# on a different subnet/VLAN than this add-on can infer — see #143 and
# Docs/design_subnet_and_hostname_resolution.md.
SCAN_SUBNET="$(bashio::config 'scan_subnet')"

{
    echo "ENV_SCHEMA_VERSION=${ENV_SCHEMA_VERSION}"
    echo "# Auto-generated by the Home Assistant add-on wrapper on every start."
    echo "# Edit values in the add-on's Configuration tab, not this file directly."
    echo ""
    echo "APP_IP=${APP_IP}"
    echo "APP_PORT=${APP_PORT}"
    echo ""
    echo "MASS_IP=${MASS_IP}"
    echo "MASS_PORT=${MASS_PORT}"
    echo "MASS_USERNAME=${MASS_USERNAME}"
    echo "MASS_PASSWORD=${MASS_PASSWORD}"
    echo "MASS_TOKEN=${MASS_TOKEN}"
    echo ""
    echo "SCAN_SUBNET=${SCAN_SUBNET}"
    echo ""
    echo "BOSE_PORT=8090"
    echo "TRUST_PROXY=true"
} > "${ENV_FILE}"

# Persist auto-detected address(es) AND the current assigned_port back into
# this add-on's own Configuration tab. The Supervisor options endpoint
# REPLACES the whole options object rather than merging (POST
# /addons/self/options -> app.options = body["options"], no merge) — so
# every known field is resent here, not just the ones that changed, to avoid
# wiping out mass_port/mass_token/mass_username/mass_password. Best-effort:
# a failure here doesn't stop boot, since .env above is already written from
# the resolved values either way.
#
# Unlike app_ip/mass_ip (which only get written back once, while blank),
# assigned_app_port is stamped on EVERY boot regardless of what's currently
# there — it's not a user-editable value, so any manual edit to it in the
# Configuration tab gets overwritten back to the real Supervisor-assigned
# port on the next restart. That's what makes it effectively read-only,
# since the Supervisor schema has no native read-only field type.
PATCH_BODY="$(jq -n \
    --arg app_ip "${APP_IP}" \
    --arg mass_ip "${MASS_IP}" \
    --argjson mass_port "${MASS_PORT:-8095}" \
    --arg mass_username "${MASS_USERNAME}" \
    --arg mass_password "${MASS_PASSWORD}" \
    --arg mass_token "${MASS_TOKEN}" \
    --arg scan_subnet "${SCAN_SUBNET}" \
    --argjson assigned_app_port "${APP_PORT:-0}" \
    '{options: {app_ip: $app_ip, mass_ip: $mass_ip, mass_port: $mass_port, mass_username: $mass_username, mass_password: $mass_password, mass_token: $mass_token, scan_subnet: $scan_subnet, assigned_app_port: $assigned_app_port}}')"

if curl -sf -X POST \
    -H "Authorization: Bearer ${SUPERVISOR_TOKEN}" \
    -H "Content-Type: application/json" \
    -d "${PATCH_BODY}" \
    http://supervisor/addons/self/options >/dev/null 2>&1; then
    bashio::log.info "Saved current address(es) and assigned port (${APP_PORT}) to the Configuration tab."
else
    bashio::log.warning "Could not save address(es)/assigned port back to Configuration — will retry next boot."
fi

export TZ
TZ="$(bashio::supervisor.timezone)"
bashio::log.info "Timezone set from Home Assistant Supervisor: ${TZ}"

bashio::log.info "Starting Bose SoundTouch Hybrid..."
cd /app || exit 1
exec node server.js
