# ==============================================================================
# BOSE SOUNDTOUCH HYBRID 2026 V3
# ==============================================================================
# --- HOW TO UPDATE THIS APP ---
# Due to how some NAS systems (like my QNAP server) aggressively cache images,
# simply clicking "Recreate" while using the 'latest' tag fails to pull the 
# newest code. If you have this problem try a method below to bypass this issue:
#
# METHOD A: IF NEEDED FOR NAS/GUI USERS (Version Tag Method)
# 1. Check the GitHub Releases page for the newest version number (e.g., :v4).
# 2. Change the word 'latest' on the image line below to that exact tag (e.g., :v4).
# 3. Click 'Recreate' or 'Update' in your Docker interface.
# 4. I'll also include a new YML for each release that will be correctly tagged.
#
# METHOD B: COMMAND LINE / LINUX USERS
# Set the tag as 'latest'. Navigate to the folder containing this file and run:
# 1. docker compose pull
# 2. docker compose up -d
# 3. docker image prune -f
# ==============================================================================

services:
  bose-hybrid:
    # Default is normally 'latest' for fresh installs. However, to force
    # an update on your NAS change it to the aspecific version (e.g., :v4)
    # Current version tag below is correct for theis release: v3
    image: ghcr.io/tjgigs/bose-soundtouch-hybrid-2026:v3
    
    container_name: bose-soundtouch-hybrid
    network_mode: "host"
    
    volumes:
      # [!] USER ACTION REQUIRED: 
      # Change ONLY the path to the LEFT of '/bose-soundtouch-hybrid' 
      # to match your specific NAS storage structure.
      - /share/Container/bose-soundtouch-hybrid:/app/config
      # - /share/Container/bose-soundtouch-hybrid/logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      
    restart: unless-stopped
